
export DRAM_PKG = bsg_dramsim3_hbm2_4gb_x128_pkg

export DRAM_FIXED_LATENCY ?= 10
export BP_SIM_CLK_PERIOD ?= 1000

export DUT_PARAMS = 
export TB_PARAMS  = \
                    -pvalue+dram_fixed_latency_p=$(DRAM_FIXED_LATENCY)

export DUT_DEFINES =
export TB_DEFINES  = +define+BP_SIM_CLK_PERIOD=$(BP_SIM_CLK_PERIOD) \
                     +define+dram_pkg=$(DRAM_PKG)

export HDL_DEFINES = $(DUT_DEFINES) $(TB_DEFINES)
export HDL_PARAMS  = $(DUT_PARAMS) $(TB_PARAMS)

